## Zelf exceptions opwerpen

We zijn ondertussen al gewend aan het opvangen van uitzonderingen met behulp van ``try`` en ``catch``. De uitzonderingen die we opvangen zijn steeds objecten van het type ``Exception`` of van een afgeleide klasse. Denk maar aan de ``NullReferenceException`` klasse die werd overgeÃ«rfd van ``Exception``.

Je kan echter ook in je eigen code **(al dan niet zelfgemaakte) uitzonderingen**  opwerpen, zodat deze elders opgevangen worden. Je kan hierbij zelf exceptions maken (zie volgende sectie) of gewoon gebruik maken van een bestaande Exception-klasse.

Een voorbeeld van een bestaand ``Exception`` type gebruiken:

```java
static int DoeIets(int getal)
{
    if (getal == 0)
        throw new DivideByZeroException("Tried dividing by 0.You shouldn't do that!");
    else
        return 100 / getal;
}
 
 
static void Main(string[] args)
{
    try
    {
        Console.WriteLine(DoeIets(0));
    }
    catch(DivideByZeroException e)
    {
        Console.WriteLine(e.Message);
    }
}
```

De uitvoer zal zijn:

```text
Tried dividing by 0. You shouldn't do that.
```


De lijn ``throw new DivideByZeroException("Tried dividing by 0.You shouldn't do that!");`` zorgt er dus voor dat we een eigen foutboodschap 'verpakken'

### Een eigen exception ontwerpen

Je kan ook eigen klassen overerven van ``Exception`` zodat je eigen uitzonderingen kan maken. Je maakt hiervoor gewoon een nieuwe klasse aan die je laat overerven van de Exception-klasse. Een voorbeeld:

```java
class Timception: Exception
{
    public override string ToString()
    {
        string extrainfo = "Exception Generated by Tim Dams:\n";
        return extrainfo+base.ToString();
    }
}
```

Om deze exception nu zelf op te werpen gebruiken we het keyword **``throw``** gevolgd door een object van het type uitzondering dat je wenst op te werpen. 

In volgende voorbeeld gooien we onze eigen exception op een bepaald punt in de code op en vangen deze dan op:

```java
static void Main(string[] args)
{
    try
    {
        TimsMethode();
    }
 
    catch (Timception e)
    {
       Console.WriteLine(e.ToString());
    }     
}
static public void TimsMethode()
{
    //do stuff
    //...
    //when suddenly: a wild exception appears
    Timception exp = new Timception();
    throw exp;
}
```

